name: NPM Publish

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@l3vels'
      - run: npm ci
      - run: npm version patch --no-git-tag-version
      - run: git config --global user.name 'ci' && git config --global user.email 'deploy@l3vels.xyz'
      - run: git add package.json package-lock.json
      - run: 'git commit -m "ci: version bump"'
      - run: git push
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
